export const ROUTES = {
  HOME: "/",
  PRODUCTS: "/products",
  ORDERS: "/orders",
  PROFILE: "/profile",
  PROFILE__EDIT_NAME: "/profile/edit-name",
  PROFILE__MY_ORDERS: "/profile/my-orders",
  PROFILE__ADDRESS: "/profile/address",
  PROFILE__ABOUT_US: "/profile/about-us",
  PROFILE__ADDRESS__ADD: "/profile/address/add",
  PROFILE__ORDER_DETAILS: "/profile/my-orders/order-details",
  OFFERS: "/offers",
  PRIVAICY_CONDITIONS: "terms-of-privacy",
  CHECKOUT: "/checkout",
};
